import MainLayout from "@/layouts/MainLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  GraduationCap,
  Code,
  Brain,
  List,
  Info
} from "lucide-react";

const AboutPage = () => {
  return (
    <MainLayout>
      <div className="container py-12">
        <div className="max-w-4xl mx-auto space-y-8">
          {/* Header */}
          <div className="text-center space-y-4">
            <h1 className="text-3xl sm:text-4xl font-bold text-slate-900">
              About the Smart Price Suggestion System
            </h1>
          </div>

          {/* Project Overview */}
          <Card className="academic-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-slate-900">
                <Info className="h-5 w-5 text-blue-600" />
                Project Overview
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-slate-600 leading-relaxed">
                The Smart Price Suggestion System is a mini project developed as part of the B.Sc Artificial Intelligence & Machine Learning curriculum.
              </p>
              <p className="text-slate-600 mt-4 leading-relaxed">
                The project focuses on implementing a pricing workflow inspired by how modern ride platforms suggest prices dynamically using backend systems and machine learning models.
              </p>
            </CardContent>
          </Card>

          {/* System Focus */}
          <Card className="academic-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-slate-900">
                <Brain className="h-5 w-5 text-blue-600" />
                System Focus
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-slate-600 leading-relaxed">
                This project demonstrates how ride price suggestions can be generated by combining travel distance, time-based factors, and contextual inputs within a machine learning–enabled system.
              </p>
            </CardContent>
          </Card>

          {/* Functional Scope */}
          <Card className="academic-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-slate-900">
                <List className="h-5 w-5 text-blue-600" />
                Functional Scope
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {[
                  "Manual price suggestion mode for controlled input testing",
                  "Automated price suggestion mode simulating real-time ride workflows",
                  "Dynamic pricing logic based on contextual inputs",
                  "System insights dashboard showing pricing activity"
                ].map((item, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <span className="h-1.5 w-1.5 rounded-full bg-blue-600 flex-shrink-0 mt-2.5" />
                    <span className="text-slate-600">{item}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          {/* Technology Overview */}
          <Card className="academic-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-slate-900">
                <Code className="h-5 w-5 text-blue-600" />
                Technology Overview
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-slate-600 leading-relaxed">
                The system is built using machine learning models, a Python-based backend, REST APIs, and a React-based frontend.
              </p>
            </CardContent>
          </Card>

          {/* Academic Context */}
          <Card className="academic-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-slate-900">
                <GraduationCap className="h-5 w-5 text-blue-600" />
                Academic Context
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-slate-600 leading-relaxed">
                This mini project is developed for academic demonstration purposes and reflects a system-level implementation inspired by real-world ride pricing platforms.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </MainLayout>
  );
};

export default AboutPage;
