import { useEffect, useState } from "react";
import MainLayout from "@/layouts/MainLayout";
import { getApiUrl } from "@/lib/api-config";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { BarChart3, LineChart, PieChart, Brain, TrendingUp, Clock, Bike, Car } from "lucide-react";
import {
  LineChart as RechartsLineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  PieChart as RechartsPieChart,
  Pie,
  Cell,
  Legend,
} from "recharts";

interface DemandTrend {
  demand: string;
  fare: number;
}

interface TimePrice {
  time_of_day: string;
  avg_fare: number;
}

interface RideDistribution {
  ride_type: string;
  count: number;
}

const Dashboard = () => {
  const [demandData, setDemandData] = useState<DemandTrend[]>([]);
  const [timeData, setTimeData] = useState<TimePrice[]>([]);
  const [rideData, setRideData] = useState<{ name: string, value: number, color: string }[]>([]);
  const [metrics, setMetrics] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [demandRes, timeRes, rideRes, metricsRes] = await Promise.all([
          fetch(getApiUrl("/api/dashboard/demand-trend")),
          fetch(getApiUrl("/api/dashboard/time-price")),
          fetch(getApiUrl("/api/dashboard/ride-distribution")),
          fetch(getApiUrl("/api/dashboard/model-metrics"))
        ]);

        const demand = await demandRes.json();
        const time = await timeRes.json();
        const ride = await rideRes.json();
        const modelMetrics = await metricsRes.json();

        // Transform data for charts
        setDemandData(demand.map((d: any) => ({ demand: d.demand_level, fare: d.avg_fare })));

        setTimeData(time);

        const colors = ["hsl(221, 83%, 53%)", "hsl(243, 75%, 59%)", "#82ca9d"];
        setRideData(ride.map((r: any, index: number) => ({
          name: r.ride_type,
          value: r.count,
          color: colors[index % colors.length]
        })));

        setMetrics(modelMetrics);
        setIsLoading(false);
      } catch (error) {
        console.error("Failed to fetch dashboard data", error);
        setIsLoading(false);
      }
    };

    fetchData();
  }, []);

  return (
    <MainLayout>
      <div className="container py-12">
        <div className="max-w-6xl mx-auto space-y-8">
          {/* Header */}
          <div className="text-center space-y-4">
            <Badge variant="secondary" className="px-4 py-2">
              <BarChart3 className="h-3.5 w-3.5 mr-2" />
              System Activity
            </Badge>
            <h1 className="text-3xl sm:text-4xl font-bold">System Insights Dashboard</h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              This dashboard provides an overview of price suggestion activity generated by the system. It displays usage patterns and pricing trends based on the data processed during ride price suggestions.
            </p>
          </div>

          {isLoading ? (
            <div className="text-center py-20 text-muted-foreground">Loading analytics...</div>
          ) : (
            <>
              {/* Model Stats */}
              <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                <Card className="academic-card">
                  <CardContent className="pt-6">
                    <div className="flex items-center gap-4">
                      <div className="h-12 w-12 rounded-lg bg-blue-50 flex items-center justify-center">
                        <Brain className="h-6 w-6 text-blue-600" />
                      </div>
                      <div>
                        <p className="text-sm text-slate-500">System Status</p>
                        <p className="font-semibold text-slate-800">Online</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card className="academic-card">
                  <CardContent className="pt-6">
                    <div className="flex items-center gap-4">
                      <div className="h-12 w-12 rounded-lg bg-green-50 flex items-center justify-center">
                        <TrendingUp className="h-6 w-6 text-green-600" />
                      </div>
                      <div>
                        <p className="text-sm text-slate-500">Average Suggested Price</p>
                        <p className="font-semibold text-green-700">₹{timeData.length > 0 ? (timeData.reduce((a, b) => a + b.avg_fare, 0) / timeData.length).toFixed(0) : 0}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card className="academic-card">
                  <CardContent className="pt-6">
                    <div className="flex items-center gap-4">
                      <div className="h-12 w-12 rounded-lg bg-blue-50 flex items-center justify-center">
                        <Clock className="h-6 w-6 text-blue-600" />
                      </div>
                      <div>
                        <p className="text-sm text-slate-500">Total Price Suggestions</p>
                        <p className="font-semibold text-slate-800">{rideData.reduce((acc, curr) => acc + curr.value, 0)}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card className="academic-card">
                  <CardContent className="pt-6">
                    <div className="flex items-center gap-4">
                      <div className="h-12 w-12 rounded-lg bg-orange-50 flex items-center justify-center">
                        <BarChart3 className="h-6 w-6 text-orange-600" />
                      </div>
                      <div>
                        <p className="text-sm text-slate-500">High Activity Period</p>
                        <p className="font-semibold text-slate-800">
                          {timeData.length > 0
                            ? timeData.reduce((p, c) => (p.avg_fare > c.avg_fare ? p : c)).time_of_day
                            : "N/A"}
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Charts Grid */}
              <div className="grid lg:grid-cols-2 gap-6">
                {/* Demand vs Fare Line Chart */}
                {/* Demand vs Fare Line Chart */}
                <Card className="academic-card">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-slate-800">
                      <LineChart className="h-5 w-5 text-blue-600" />
                      Pricing Activity Trend
                    </CardTitle>
                    <CardDescription className="text-slate-500">
                      Overview of pricing adjustments based on demand levels
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="h-[300px]">
                      <ResponsiveContainer width="100%" height="100%">
                        <RechartsLineChart data={demandData}>
                          <CartesianGrid strokeDasharray="3 3" className="stroke-slate-200" />
                          <XAxis
                            dataKey="demand"
                            tick={{ fontSize: 12, fill: '#64748b' }}
                            className="text-slate-500"
                          />
                          <YAxis
                            tick={{ fontSize: 12, fill: '#64748b' }}
                            className="text-slate-500"
                            label={{ value: '₹ Fare', angle: -90, position: 'insideLeft', fill: '#64748b' }}
                          />
                          <Tooltip
                            contentStyle={{
                              backgroundColor: '#ffffff',
                              border: '1px solid #e2e8f0',
                              borderRadius: '8px',
                              color: '#1e293b'
                            }}
                          />
                          <Line
                            type="monotone"
                            dataKey="fare"
                            stroke="#2563eb"
                            strokeWidth={2}
                            dot={{ fill: "#2563eb", r: 4 }}
                            activeDot={{ r: 6 }}
                          />
                        </RechartsLineChart>
                      </ResponsiveContainer>
                    </div>
                  </CardContent>
                </Card>

                {/* Time vs Price Bar Chart */}
                {/* Time vs Price Bar Chart */}
                <Card className="academic-card">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-slate-800">
                      <BarChart3 className="h-5 w-5 text-blue-600" />
                      Suggested Price Over Time
                    </CardTitle>
                    <CardDescription className="text-slate-500">
                      Shows how suggested prices vary across different time periods
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="h-[300px]">
                      <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={timeData}>
                          <CartesianGrid strokeDasharray="3 3" className="stroke-slate-200" />
                          <XAxis dataKey="time_of_day" tick={{ fontSize: 12, fill: '#64748b' }} />
                          <YAxis tick={{ fontSize: 12, fill: '#64748b' }} label={{ value: '₹', angle: -90, position: 'insideLeft', fill: '#64748b' }} />
                          <Tooltip
                            contentStyle={{
                              backgroundColor: '#ffffff',
                              border: '1px solid #e2e8f0',
                              borderRadius: '8px',
                              color: '#1e293b'
                            }}
                          />
                          <Bar dataKey="avg_fare" name="Avg Fare" fill="#3b82f6" radius={[4, 4, 0, 0]} />
                        </BarChart>
                      </ResponsiveContainer>
                    </div>
                  </CardContent>
                </Card>

                {/* Ride Type Distribution */}
                <Card className="academic-card">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-slate-800">
                      <PieChart className="h-5 w-5 text-blue-600" />
                      Ride Type Distribution
                    </CardTitle>
                    <CardDescription className="text-slate-500">
                      Displays the distribution of price suggestions across ride types
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="h-[300px]">
                      <ResponsiveContainer width="100%" height="100%">
                        <RechartsPieChart>
                          <Pie
                            data={rideData}
                            cx="50%"
                            cy="50%"
                            labelLine={false}
                            outerRadius={100}
                            fill="#8884d8"
                            dataKey="value"
                            label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                          >
                            {rideData.map((entry, index) => (
                              <Cell key={`cell-${index}`} fill={entry.color} />
                            ))}
                          </Pie>
                          <Legend wrapperStyle={{ color: '#475569' }} />
                          <Tooltip
                            contentStyle={{
                              backgroundColor: '#ffffff',
                              border: '1px solid #e2e8f0',
                              borderRadius: '8px',
                              color: '#1e293b'
                            }}
                          />
                        </RechartsPieChart>
                      </ResponsiveContainer>
                    </div>
                  </CardContent>
                </Card>

                {/* Model Info Card */}
                {/* System Summary Card */}
                <Card className="academic-card">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-slate-800">
                      <Brain className="h-5 w-5 text-blue-600" />
                      System Summary
                    </CardTitle>
                    <CardDescription className="text-slate-500">
                      Summarizes system activity based on recent interactions
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <span className="text-sm text-slate-600">System Uptime</span>
                        <Badge variant="secondary" className="bg-green-50 text-green-700 border-green-200">99.9%</Badge>
                      </div>
                      <div className="w-full bg-slate-100 rounded-full h-2">
                        <div className="bg-green-600 h-2 rounded-full" style={{ width: '99%' }} />
                      </div>
                    </div>

                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <span className="text-sm text-slate-600">Active Data Streams</span>
                        <Badge variant="secondary" className="bg-slate-100 text-slate-700 border-slate-200">Online</Badge>
                      </div>
                      <div className="w-full bg-slate-100 rounded-full h-2">
                        <div className="bg-blue-600 h-2 rounded-full" style={{ width: '100%' }} />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </>
          )}

          <div className="text-center pt-8 border-t border-slate-200">
            <p className="text-sm text-slate-500 italic">
              This view simulates how pricing data may be monitored within a ride platform’s internal system.
            </p>
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default Dashboard;
